name: Scary IT Things
description: Here be dragons
markdown: kramdown
paginate: 5
paginate_path: page/:num/
permalink: :year/:month/:day/:title

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
